# Generated by Django 5.1.7 on 2025-04-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0002_alter_huesped_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='placas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Licencia', 'Licencia de Conducir'), ('Otro', 'Otro')], default='DNI', max_length=20),
        ),
    ]
