# Generated by Django 5.1.7 on 2025-04-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0003_remove_huesped_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='tipo_documento',
            field=models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Pasaporte', 'Pasaporte'), ('Cedula Extranjera', 'Cedula Extranjera'), ('Registro civil', 'Registro civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], default='Cedula de ciudadania', max_length=30),
        ),
    ]
