# Generated by Django 5.1.7 on 2025-04-18 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0004_alter_huesped_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='huesped',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
