# Generated by Django 5.1.7 on 2025-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0005_huesped_fecha_entrada_huesped_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
