# Generated by Django 5.2.5 on 2025-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0007_alter_huesped_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
