# Generated by Django 5.1.7 on 2025-04-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_huesped_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendarestaurantebar',
            name='huesped',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tiendarestaurantebar',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='tiendarestaurantebar',
            name='habitacion',
        ),
        migrations.DeleteModel(
            name='Huesped',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='TiendaRestauranteBar',
        ),
    ]
