# Generated by Django 5.1.7 on 2025-04-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_remove_tiendarestaurantebar_huesped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
