# Generated by Django 5.1.7 on 2025-04-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_alter_habitacion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
