# Generated by Django 5.1.7 on 2025-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0006_actualizar_descripciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
