# Generated by Django 5.1.7 on 2025-04-03 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0007_alter_habitacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['numero'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='tipo_habitacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('aseo', 'En Aseo'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado de la Habitación'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('familiar', 'Familiar'), ('pareja', 'Pareja'), ('suite', 'Suite'), ('individual', 'Individual')], default=(('familiar', 'Familiar'),), max_length=20, verbose_name='Tipo de Habitación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad Máxima'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de Habitación'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por Noche'),
        ),
    ]
