# Generated by Django 5.1.7 on 2025-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0008_alter_habitacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/', verbose_name='Imagen de la Habitación'),
        ),
    ]
