# Generated by Django 5.1.7 on 2025-04-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0009_habitacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen',
        ),
    ]
