# Generated by Django 5.1.7 on 2025-04-14 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0008_alter_habitacion_options_and_more'),
        ('huespedes', '0004_alter_huesped_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Consumo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='habitaciones.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='huespedes.huesped', verbose_name='Huésped (opcional)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['-fecha_consumo'],
            },
        ),
    ]
