# Generated by Django 5.1.7 on 2025-04-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
