# Generated by Django 5.1.7 on 2025-04-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0002_producto_disponible'),
        ('productos', '0003_categoria_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total del Consumo'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
