# Generated by Django 5.1.7 on 2025-04-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0003_alter_consumo_producto_consumo_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='estado',
            field=models.CharField(choices=[('consumido', 'Consumido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
