# Generated by Django 5.1.7 on 2025-04-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0004_consumo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='estado',
        ),
    ]
