# Generated by Django 5.1.7 on 2025-04-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0005_remove_consumo_estado'),
        ('huespedes', '0007_alter_huesped_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='huesped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='huespedes.huesped', verbose_name='Huésped (opcional)'),
        ),
    ]
