# Generated by Django 5.1.7 on 2025-04-15 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para identificar el producto.', max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del producto.', null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='El precio debe ser un valor positivo, en formato decimal.', max_digits=10, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, help_text='Indica si el producto está disponible para la venta.', verbose_name='Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el producto.', verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que se realizó la última actualización del producto.', verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría opcional para organizar los productos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'), models.Index(fields=['categoria'], name='productos_p_categor_17b5fc_idx')],
            },
        ),
    ]
