# Generated by Django 5.1.7 on 2025-04-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del producto (opcional).', null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
