# Generated by Django 5.1.7 on 2025-04-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la categoría está activa o no.', verbose_name='Activo'),
        ),
    ]
