# Generated by Django 5.1.7 on 2025-04-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0011_habitacion_imagen'),
        ('productos', '0003_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='habitacion',
            field=models.ForeignKey(blank=True, help_text='Habitación a la que pertenece este producto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='habitaciones.habitacion', verbose_name='Habitación asociada'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['habitacion'], name='productos_p_habitac_86f530_idx'),
        ),
    ]
