# Generated by Django 5.1.7 on 2025-04-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0007_alter_huesped_fecha_salida'),
        ('productos', '0004_producto_habitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_habitac_86f530_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='habitacion',
        ),
        migrations.AddField(
            model_name='consumo',
            name='huesped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_productos', to='huespedes.huesped', verbose_name='Huésped'),
        ),
    ]
